### PR TITLE
Add npm support

### PR DESCRIPTION
**Pull request by mattlewis92**

### CODE REVIEW

**Comment by davej** [comment]
Awesome! Does usage work like this?

```js
const angular = require('angular');
const classy = require('angular-classy')

const app = angular.module('app', [classy]);
```

**Comment by mattlewis92** [comment]
Yup 😄

**Comment by mattlewis92** [comment]
Awesome, thanks for the quick response! You'll just need to checkout the repo now and run `npm publish` to get it on npm 😄

**Comment by davej** [comment]
Cool, published as [`v1.2.4`](https://github.com/davej/angular-classy/releases/tag/v1.2.4).

**Comment by mattlewis92** [comment]
Thanks! :octocat:

**Comment by davej** [comment]
Should `angular` also be moved out of `dependencies` and into  `peerDependencies` and `devDependencies` instead?

**Comment by mattlewis92** [comment]
It doesn't look like it's in the dependencies list currently, you'd only need to add it to dev dependencies if you're using commonjs in your build process. Adding it to peer dependencies wouldn't add much really as for 99% of apps angular will already be installed.

**Comment by davej** [comment]
Ah, you're right, I was looking at the `bower.json` at the time.

Thanks!

**Pull request merged**
